modulo03-python-web/20240310-aula10/agenda/urls.py
from django.urls import path

from . import views

app_name = "agenda"

urlpatterns = [
    path("", views.index, name="index"),
    path("meus-agendamentos/", views.agendamentos, name="meus_agendamentos"),
    path("agendamentos/<int:agendamento_id>/", views.detalhe_agendamento, name="detalhe_agendamento"),
    path("agendamentos/<int:agendamento_id>/cancelar", views.cancelar_agendamento, name="cancelar_agendamento"),
    path("agendamentos/agenda", views.agenda, name="agenda")
]

modulo03-python-web/20240310-aula10/agendamento/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

    path('__debug__/', include('debug_toolbar.urls')),

    path('agenda/', include('agenda.urls')),
    path('registro/', include('registro.urls'))
]

modulo03-python-web/20240310-aula10/agenda/models.py
from django.db import models

# Model que representa a tabela auth_user
from django.contrib.auth.models import User

class Servico(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=200)
    habilitado = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.nome

    class Meta:
        db_table = "tb_servicos"


class Agenda(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    servico = models.ForeignKey(Servico, on_delete=models.SET_NULL, null=True)
    data_hora_inicial = models.DateTimeField()
    data_hora_final = models.DateTimeField()

    def __str__(self) -> str:
        data = self.data_hora_inicial.strftime("%d/%m/%Y")
        hora_inicial = self.data_hora_inicial.strftime("%H:%M")
        hora_final = self.data_hora_final.strftime("%H:%M")
        
        return f"{self.servico} ({self.usuario.first_name} {data} {hora_inicial} - {hora_final})"

    class Meta:
        db_table = "tb_agendamentos"


class StatusAgendamento(models.Model):

    A_CONFIRMAR = "a_confirmar"
    AGENDADO = "agendado"
    CONCLUIDO = "concluido"
    CANCELADO_PELO_CLIENTE = "cancelado_pelo_cliente"
    CANCELADO_PELO_PROFISSIONAL = "cancelado_pelo_profissional"

    POSSIVEIS_STATUS_AGENDAMENTO = {
        A_CONFIRMAR: "A confirmar",
        AGENDADO: "Agendado",
        CONCLUIDO: "Concluído",
        CANCELADO_PELO_CLIENTE: "Cancelado pelo cliente",
        CANCELADO_PELO_PROFISSIONAL: "Cancelado pelo profissional"
    }

    agenda = models.OneToOneField(Agenda, on_delete=models.CASCADE, primary_key=True)
    status = models.CharField(max_length=100, choices=POSSIVEIS_STATUS_AGENDAMENTO)
    descricao = models.CharField(max_length=200, null=True, blank=True)

    def get_status(self) -> str:
        return self.POSSIVEIS_STATUS_AGENDAMENTO.get(self.status)
    
    def cancelavel(self) -> bool:
        return self.status in [self.A_CONFIRMAR, self.AGENDADO]

    def __str__(self) -> str:
        return f"{self.agenda} ({self.POSSIVEIS_STATUS_AGENDAMENTO[self.status]})"

    class Meta:
        db_table = "tb_status_agendamentos"

modulo03-python-web/20240310-aula10/agenda/views.py
import calendar

from datetime import datetime

from django.db.models import Q
from django.http import HttpRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone

from .models import Agenda, StatusAgendamento
from .utils import gerar_lista_horarios

def index(request):
    return render(request, "agenda/index.html")


def agendamentos(request: HttpRequest):

    agenda_usuario = Agenda.objects.filter(
        usuario=request.user
    )

    return render(
        request,
        "agenda/agendamentos.html",
        {"agenda_usuario": agenda_usuario}
    )

def detalhe_agendamento(request: HttpRequest, agendamento_id: int):

    agendamento = Agenda.objects.get(pk=agendamento_id)

    if agendamento.usuario == request.user:
        return render(
            request,
            "agenda/detalhe_agendamento.html",
            {"agendamento": agendamento}
        )
    
    else:
        return redirect(reverse("agenda:meus_agendamentos"))
    
def cancelar_agendamento(request: HttpRequest, agendamento_id: int):

    agendamento = get_object_or_404(Agenda, pk=agendamento_id)
    
    if request.method == "GET":
        return render(
            request,
            "agenda/cancelar_agendamento.html",
            {"agendamento": agendamento}
        )
    
    if request.method == "POST":
        motivo_cancelamento = request.POST.get("motivo_cancelamento")

        status_agendamento = agendamento.statusagendamento
        status_agendamento.descricao = motivo_cancelamento
        status_agendamento.status = StatusAgendamento.CANCELADO_PELO_CLIENTE

        status_agendamento.save()

        return redirect(reverse("agenda:meus_agendamentos"))

def agenda(request):
    data_atual = timezone.now()
    ano_atual = data_atual.year
    mes_atual = data_atual.month

    tipo_visualizacao = request.GET.get("visualizacao", "mensal")

    calendario = calendar.Calendar(firstweekday=calendar.SUNDAY)
    agenda = calendario.monthdatescalendar(ano_atual, mes_atual)

    match tipo_visualizacao:
        case "mensal":
            return render(
                request,
                "agenda/agenda_mensal.html",
                {
                    "agenda": agenda,
                    "data_atual": data_atual
                }
            )

        case "semanal":
            
            semana_escolhida = 1
            dias_semana = []

            for indice, semana in enumerate(agenda, start=1):
                for data in semana:
                    if data_atual.date() == data:
                        semana_escolhida = indice

            for data in agenda[semana_escolhida-1]:
                dias_semana.append(data)

            data_hora_inicial = datetime.combine(dias_semana[0], datetime.min.time())
            data_hora_final = datetime.combine(dias_semana[-1], datetime.max.time())

            agendas_usuario = Agenda.objects.filter(
                Q(statusagendamento__status=StatusAgendamento.A_CONFIRMAR) | Q(statusagendamento__status=StatusAgendamento.AGENDADO)
            ).filter(
                data_hora_inicial__gte=data_hora_inicial,
                data_hora_final__lte=data_hora_final
            )

            return render(
                request,
                "agenda/agenda_semanal.html",
                {
                    "dias_semana": dias_semana,
                    "lista_horarios": gerar_lista_horarios(dias_semana, agendas_usuario)
                }
            )

modulo03-python-web/20240310-aula10/agenda/templates/agenda/agenda_base.html
<h1 class="text-center">Agenda</h1>
    <div class="row mt-5 text-center">
        <div class="col"><a href="#">Anterior</a> | <a href="#">Próximo</a></div>
        <div class="col">{% block texto_agenda %}{% endblock texto_agenda %}</div>
        <div class="col">
            <a href="{% url "agenda:agenda" %}?visualizacao=mensal">Mensal</a> |
            <a href="{% url "agenda:agenda" %}?visualizacao=semanal">Semanal</a> |
            <a href="#">Diária</a>
        
        </div>
    </div>

modulo03-python-web/20240310-aula10/agenda/templates/agenda/agenda_mensal.html
{% extends "base.html" %}

{% block conteudo %}
    {% include "agenda/agenda_base.html" %}
    <div class="row bg-light fw-bold mt-3">
        <div class="col text-center border border-1">Dom</div>
        <div class="col text-center border border-1">Seg</div>
        <div class="col text-center border border-1">Ter</div>
        <div class="col text-center border border-1">Qua</div>
        <div class="col text-center border border-1">Qui</div>
        <div class="col text-center border border-1">Sex</div>
        <div class="col text-center border border-1">Sáb</div>
    </div>
    {% for semana in agenda %}
        <div class="row">
            {% for data in semana %}
                <div class="col text-center border border-1"><span class="{% if data.month == data_atual.month %}{% else %}opacity-25{% endif %}">{{ data.day }}</span></div>
            {% endfor %}
        </div>
    {% endfor %}

{% endblock conteudo %}

modulo03-python-web/20240310-aula10/agenda/templates/agenda/agenda_semanal.html
{% extends "base.html" %}

{% block conteudo %}
    {% include "agenda/agenda_base.html" %}
    <div class="row bg-light fw-bold mt-3">
        <div class="col">Horário</div>
        {% for data in dias_semana %}
            <div class="col text-center border border-1">{{ data.day }}/{{ data|date:"m" }}</div>
        {% endfor %}
    </div>
    {% for horario in lista_horarios %}
        <div class="row bg-light fw-bold">
            <div class="col">{{ horario.hora }}</div>
            {% for agenda in horario.agendas %}
                <div class="col text-center border border-1">{{ agenda|default:"" }}</div>
            {% endfor %}
        </div>
    {% endfor %}
    

{% endblock conteudo %}

modulo03-python-web/20240310-aula10/agenda/templates/agenda/agendamentos.html
{% extends "base.html" %}

{% block conteudo %}
    <h1 class="text-center">Agendamentos do usuário {{ user }}</h1>

    <div class="row row-cols-3 justify-content-center">
        {% for agenda in agenda_usuario %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <h5 class="card-title">{{ agenda.servico }}</h5>
                      <h6 class="card-subtitle mb-2 text-body-secondary">{{ agenda.data_hora_inicial|date:"d/m/Y H:i" }} - {{ agenda.data_hora_final|date:"H:i" }}</h6>
                      <p class="card-text">Status: {{ agenda.statusagendamento.get_status }}</p>
                      <a href="{% url 'agenda:detalhe_agendamento' agenda.id %}" class="card-link">Detalhes desse agendamento</a>
                    </div>
                  </div>
            </div>
        {% endfor %}
    </div>

{% endblock conteudo %}

modulo03-python-web/20240310-aula10/agenda/templates/agenda/cancelar_agendamento.html
{% extends "base.html" %}

{% block conteudo %}
<h2 class="text-center">Cancelar o agendamento {{ agendamento.id|stringformat:"05d" }}?</h2>

<div class="row">
    <div class="col text-center">Descrição: {{ agendamento }}</div>
</div>
<form action="{% url 'agenda:cancelar_agendamento' agendamento.id %}" method="POST">
    <div class="row mt-3">
        {% csrf_token %}
        <div class="col form-floating">
            <textarea name="motivo_cancelamento" id="motivo_cancelamento" cols="30" rows="10" class="form-control" placeholder="Motivo do cancelamento"></textarea>
            <label class="ms-2" for="motivo_cancelamento">Motivo do cancelamento: </label>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col">
            <button type="submit" class="btn btn-primary">Cancelar</button>
        </div>
    </div>
</form>

</div>
{% endblock conteudo %}

modulo03-python-web/20240310-aula10/agenda/templates/agenda/detalhe_agendamento.html
{% extends "base.html" %}

{% block conteudo %}
    <h3 class="text-center">Detalhe agendamento #{{ agendamento.id|stringformat:"05d" }}</h3>
    <hr>

    <div class="row">
        <div class="col d-grid justify-content-center">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">{{ agendamento.servico.nome }}</h5>
                  <h6 class="card-subtitle mb-2 text-body-secondary">{{ agendamento.data_hora_inicial|date:"d/m/Y H:i" }} - {{ agendamento.data_hora_final|date:"H:i" }}</h6>
                  <p class="card-text">Status: {{ agendamento.statusagendamento.get_status }}</p>
                  {% if agendamento.statusagendamento.cancelavel %}
                    <a href="{% url 'agenda:cancelar_agendamento' agendamento.id %}" class="card-link">Cancelar esse agendamento</a>
                  {% endif %}
                </div>
              </div>
        </div>
    </div>
{% endblock conteudo %}

modulo03-python-web/20240310-aula10/agenda/templates/agenda/index.html
{% extends "base.html" %}

{% block conteudo %}
    <h2>Sistema de Agendamento</h2>
    {% if user.is_authenticated %}
        <h5>Você está autenticado como {{ user.username }}. Seu email é {{ user.email }}.</h5>
        <form action="{% url "logout" %}" method="POST">
            {% csrf_token %}
            <button type="submit">Efetuar logout</button>
        </form>
    {% else %}
        <h5><a href="{% url "login" %}">Ir para a página de login</a></h5>
    {% endif %}

{% endblock conteudo %}