modulo03-python-web/20231217-aula01/enquetes/urls.py
from django.urls import path

from . import views

app_name = "enquetes"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pergunta_id>/", views.detalhe, name="detalhe"),
    path("<int:pergunta_id>/resultados", views.resultados, name="resultados"),
    path("<int:pergunta_id>/votar", views.votar, name="votar")
]

modulo03-python-web/20231217-aula01/estatisticas/urls.py
from django.urls import path

from . import views

app_name = "estatisticas"

urlpatterns = [
    path("", views.index, name="index"),
]

modulo03-python-web/20231217-aula01/meusite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("enquetes/", include("enquetes.urls")),
    path("estatisticas/", include("estatisticas.urls")),
]

modulo03-python-web/20231217-aula01/enquetes/models.py
from django.db import models

class Pergunta(models.Model):
    
    texto_pergunta = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField("Data de publicação")

    class Meta:
        db_table = "tb_perguntas"

    def __str__(self):
        return self.texto_pergunta
    


class Opcao(models.Model):

    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto_opcao = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    class Meta:
        db_table = "tb_opcoes"

    def __str__(self) -> str:
        return self.texto_opcao

modulo03-python-web/20231217-aula01/enquetes/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Opcao, Pergunta

def index(request):
    todas_as_perguntas = Pergunta.objects.order_by("-data_publicacao")

    contexto = {"todas_as_perguntas": todas_as_perguntas}

    return render(request, "enquetes/index.html", contexto)


def detalhe(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    return render(request, "enquetes/detalhes.html", {"pergunta": pergunta})


def resultados(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    return render(
        request,
        "enquetes/resultados.html",
        {
            "pergunta": pergunta
        }
    )


def votar(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)

    try:
        opcao_escolhida = pergunta.opcao_set.get(pk=request.POST["opcao"])

    except (KeyError, Opcao.DoesNotExist):
        return render(
            request,
            "enquetes/detalhes.html",
            {
                "pergunta": pergunta,
                "mensagem_erro": "Você deve escolher uma opção!"
            }
        )

    else:
        opcao_escolhida.votos += 1
        opcao_escolhida.save()

        return HttpResponseRedirect(
            reverse("enquetes:resultados", args=(pergunta.id,))
        )

modulo03-python-web/20231217-aula01/estatisticas/views.py
from django.db.models import Avg, Count
from django.shortcuts import render

from enquetes.models import Opcao, Pergunta

def index(request):

    quantidade_de_perguntas = Pergunta.objects.count()
    quantidade_de_opcoes = Opcao.objects.count()
    perguntas_ordenadas_por_votos = Pergunta.objects.annotate(
        num_votos=Count('opcao__votos')
    ).order_by('-num_votos')
    media_opcoes_por_pergunta = Pergunta.objects.annotate(
        num_opcoes=Count('opcao')
    ).aggregate(media_opcoes=Avg('num_opcoes'))

    contexto = {
        "quantidade_de_perguntas": quantidade_de_perguntas,
        "quantidade_de_opcoes": quantidade_de_opcoes,
        "perguntas_ordenadas_por_votos": perguntas_ordenadas_por_votos,
        "media_opcoes_por_pergunta": media_opcoes_por_pergunta["media_opcoes"]
    }

    return render(
        request,
        "estatisticas/index.html",
        contexto,
    )

modulo03-python-web/20231217-aula01/enquetes/templates/enquetes/detalhes.html
<form action="{% url 'enquetes:votar' pergunta.id %}" method="POST">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ pergunta.texto_pergunta }}</h1></legend>
        {% if mensagem_erro %}
            <p><strong>{{ mensagem_erro }}</strong></p>
        {% endif %}

        {% for opcao in pergunta.opcao_set.all %}
            <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value={{ opcao.id }}>
            <label for="opcao{{ forloop.counter }}">{{ opcao.texto_opcao }}</label><br>
        {% endfor %}
    </fieldset><br> 
    <input type="submit" value="Votar">
</form>

<hr>
<a href="{% url 'enquetes:index' %}">Ir para a página principal</a>

modulo03-python-web/20231217-aula01/enquetes/templates/enquetes/index.html
{% if todas_as_perguntas %}
    <ul>
        {% for pergunta in todas_as_perguntas %}
            <li><a href="{% url 'enquetes:detalhe' pergunta.id %}">{{ pergunta.texto_pergunta }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>Não há perguntas cadastradas.</p>
{% endif %}

<hr>

<h2><a href="{% url 'estatisticas:index' %}">Estatísticas do site</a></h2>

modulo03-python-web/20231217-aula01/enquetes/templates/enquetes/resultados.html
<h1>{{ pergunta }}</h1>
<hr>

<ul>
    {% for opcao in pergunta.opcao_set.all %}
        <li>{{ opcao.texto_opcao }} -- {{ opcao.votos }} voto{{ opcao.votos|pluralize }}.</li>
    {% endfor %}
</ul>

<hr>
<a href="{% url 'enquetes:detalhe' pergunta.id %}">Votar novamente</a><br>
<a href="{% url 'enquetes:index' %}">Ir para a página principal</a>

modulo03-python-web/20231217-aula01/estatisticas/templates/estatisticas/index.html
<h1>Estatísticas</h1>
<hr>

{% if quantidade_de_perguntas %}
    <h2>Quantidade de perguntas cadastradas:</h2>
    <h3>{{ quantidade_de_perguntas }}</h3>

    <h2>Quantidade de opções cadastradas:</h2>
    <h3>{{ quantidade_de_opcoes }}</h3>

    <h2>Lista de perguntas ordenadas pela quantidade de votos:</h2>
    <ul>
        {% for pergunta in perguntas_ordenadas_por_votos %}
        <li>{{ pergunta }}</li>
        {% endfor %}
    </ul>

    <h2>Média de opções por pergunta</h2>
    <h3>{{ media_opcoes_por_pergunta }}</h3>
{% else %}
    <h1>Não há perguntas cadastradas</h1>
{% endif %}

<hr>    
<a href="{% url 'enquetes:index' %}">Ir para a página principal</a>