modulo03-python-web/20240310-aula10/agenda/urls.py
from django.urls import path

from . import views

app_name = "agenda"

urlpatterns = [
    path("", views.index, name="index"),
    path("meus-agendamentos/", views.agendamentos, name="meus_agendamentos"),
    path("agendamentos/<int:agendamento_id>/", views.detalhe_agendamento, name="detalhe_agendamento"),
    path("agendamentos/<int:agendamento_id>/cancelar", views.cancelar_agendamento, name="cancelar_agendamento"),
    path("agendamentos/agenda", views.agenda, name="agenda")
]

modulo03-python-web/20240310-aula10/agendamento/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

    path('__debug__/', include('debug_toolbar.urls')),

    path('agenda/', include('agenda.urls')),
    path('registro/', include('registro.urls'))
]

modulo03-python-web/20240310-aula10/registro/urls.py
from django.urls import path

from . import views

app_name = "registro"

urlpatterns = [
    path("pre-registro/", views.pre_registro, name="pre_registro"),
    path("envio-email-pre-registro/", views.envio_email_pre_registro, name="envio_email_pre_registro"),
    path("confirmacao-pre-registro/", views.registro, name="registro"),
    path("reenviar-pre-registro/<uuid>/", views.reenviar_pre_registro, name="reenviar_pre_registro"),
    path("sucesso-registro/", views.sucesso_registro, name="sucesso_registro"),
    path("me/perfil/", views.perfil, name="perfil_usuario"),
]

modulo03-python-web/20240310-aula10/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>{% block titulo %}Sistema de agendamento{% endblock titulo %}</title>
</head>
<body>

    <div class="container">
        {% if user.is_authenticated %}
            {% include "navbar.html" %}
        {% endif %}

        {% block conteudo %}{% endblock conteudo %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</body>
</html>

modulo03-python-web/20240310-aula10/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "agenda:index" %}">Página Principal</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "agenda:agenda" %}">Agendar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'agenda:meus_agendamentos' %}">Meus Agendamentos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "registro:perfil_usuario" %}">Perfil</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>