modulo03-python-web/20240121-aula04/dados/urls.py
from django.urls import path

from . import views

app_name = "dados"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:ano>/", views.lista_rodadas, name="lista_rodadas"),
    path("<int:ano>/<int:rodada_id>/", views.detalhe_rodada, name="detalhe_rodada")
]

modulo03-python-web/20240121-aula04/dados_brasileirao/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dados/', include('dados.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modulo03-python-web/20240121-aula04/dados/models.py
from django.db import models

class Clube(models.Model):
    nome = models.CharField(max_length=100)
    escudo = models.CharField(max_length=100, default="generico.svg")

    def __str__(self) -> str:
        return self.nome
    
    class Meta:
        db_table = "tb_clubes"


class Rodada(models.Model):
    numero = models.IntegerField(null=True)
    ano = models.IntegerField(null=True)

    def __str__(self) -> str:
        return f"Rodada {self.numero} do campeonato brasileiro de {self.ano}."
    
    class Meta:
        db_table = "tb_rodadas"


class Partida(models.Model):
    rodada = models.ForeignKey(Rodada, on_delete=models.SET_NULL, null=True)
    clube_mandante = models.ForeignKey(Clube, on_delete=models.SET_NULL, null=True, related_name="clube_mandante")
    clube_visitante = models.ForeignKey(Clube, on_delete=models.SET_NULL, null=True, related_name="clube_visitante")
    gols_clube_mandante = models.IntegerField(default=0)
    gols_clube_visitante = models.IntegerField(default=0)
    estadio = models.CharField(max_length=200, null=True, blank=True)
    data_hora = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.clube_mandante.nome} {self.gols_clube_mandante} X {self.gols_clube_visitante} {self.clube_visitante.nome}"
    
    class Meta:
        db_table = "tb_partidas"

modulo03-python-web/20240121-aula04/dados/views.py
from django.shortcuts import get_object_or_404, render

from dados.models import Partida, Rodada

def index(request):

    todos_anos = Rodada.objects.values("ano").distinct()
    anos = [ano_info.get("ano") for ano_info in todos_anos]
    anos.sort()

    return render(request, "dados/index.html", {"anos": anos})


def lista_rodadas(request, ano):
    todas_rodadas = Rodada.objects.filter(ano=ano).order_by("numero")

    return render(request, "dados/lista_rodadas.html", {"ano": ano, "todas_rodadas": todas_rodadas})


def detalhe_rodada(request, ano, rodada_id):
    rodada = get_object_or_404(Rodada, pk=rodada_id, ano=ano)
    todas_partidas = Partida.objects.filter(rodada=rodada)

    return render(
        request,
        "dados/detalhe_rodada.html",
        {
            "rodada": rodada,
            "todas_partidas": todas_partidas
        }
    )

modulo03-python-web/20240121-aula04/dados/templates/dados/detalhe_rodada.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}Resultados da rodada {{ rodada.numero }}{% endblock titulo %}

{% block principal %}
    <div>
        <h1>Lista de Partidas da rodada {{ rodada.numero }}</h1>
        <hr>
    </div>

    <div class="lista-partidas-rodada">
        {% for partida in todas_partidas %}
        <div class="item-partida-rodada">
            <div class="partida-rodada">
                <p><img class="img-partida" src="{% get_static_prefix %}dados/img/{{ partida.clube_mandante.escudo }}">{{ partida.clube_mandante }} {{ partida.gols_clube_mandante}} X {{ partida.gols_clube_visitante }} {{ partida.clube_visitante }} <img class="img-partida" src="{% get_static_prefix %}dados/img/{{ partida.clube_visitante.escudo }}"></p> 
            </div>
            <div class="estadio-partida-rodada">
                <p>Partida realizada no estádio {{ partida.estadio }} em {{ partida.data_hora|date:"H:i d/m/Y" }}</p>
            </div>
        </div>
        <hr>
        {% endfor %}
    </div>
    <div>
        <a href="{% url "dados:lista_rodadas" rodada.ano %}">Voltar para o detalhe da rodada</a>
        <a href="{% url "dados:index" %}">Voltar para a página principal</a>
    </div>
{% endblock principal %}

modulo03-python-web/20240121-aula04/dados/templates/dados/index.html
{% extends "base.html" %}

{% block principal %}

    <h1>Dados do Brasileirão</h1>
    <hr>

    {% if anos %}
        <div>
            {% for ano in anos %}
                <div>
                    <a href="{% url "dados:lista_rodadas" ano %}">Campeonato Brasileiro de {{ ano }}.</a>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h1>Não há dados a serem exibidos.</h1>
    {% endif %}

{% endblock principal %}

modulo03-python-web/20240121-aula04/dados/templates/dados/lista_rodadas.html
{% extends "base.html" %}

{% block titulo %}Rodadas do Campeonato Brasileiro de {{ ano }}{% endblock titulo %}

{% block principal %}
    <div>
        <h1>Campeonato Brasileiro de {{ ano }} - Rodadas</h1>
        <hr>
    </div>

    <div>
        {% for rodada in todas_rodadas %}
            <div>
                <a href="{% url "dados:detalhe_rodada" ano rodada.id %}">Resultados da rodada {{ rodada.numero }} do Campeonato Brasileiro de {{ ano }}.</a>
            </div>
        {% endfor %}
    </div>
    <hr>
    <div>
        <a href="{% url "dados:index" %}">Voltar para a página principal</a>
    </div>
{% endblock principal %}

modulo03-python-web/20240121-aula04/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}Dados do Brasileirão 2003-2023{% endblock titulo %}Dados do Brasileirão</title>
    <link rel="stylesheet" href="{% static "dados/css/dados.css" %}">
</head>
<body>
    {% block principal %}{% endblock principal %}
    
</body>
</html>